name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your.server.ip >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh user@your.server.ip << 'EOF'
            cd /path/to/your/app
            git pull origin main
            bundle install
            RAILS_ENV=production bundle exec rake db:migrate
            RAILS_ENV=production bundle exec rails assets:precompile
            sudo systemctl restart puma # hoặc passenger/nginx/unicorn
          EOF